// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyx0jSPQ5IaTsUQbpaDrDwPnRP7qCWGnU',
    appId: '1:833820909585:web:cda0d87b9d6117601791b0',
    messagingSenderId: '833820909585',
    projectId: 'mailforfinal-7bf12',
    authDomain: 'mailforfinal-7bf12.firebaseapp.com',
    storageBucket: 'mailforfinal-7bf12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUuntgCUYT9x9hP11HRfNJXR6kvH0JtgY',
    appId: '1:833820909585:android:1502f763066197751791b0',
    messagingSenderId: '833820909585',
    projectId: 'mailforfinal-7bf12',
    storageBucket: 'mailforfinal-7bf12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqWn5D5AuT-V_RM0ilV93oubZL0NGBPaw',
    appId: '1:833820909585:ios:1c82dda0db1681c51791b0',
    messagingSenderId: '833820909585',
    projectId: 'mailforfinal-7bf12',
    storageBucket: 'mailforfinal-7bf12.firebasestorage.app',
    iosBundleId: 'com.example.mail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqWn5D5AuT-V_RM0ilV93oubZL0NGBPaw',
    appId: '1:833820909585:ios:1c82dda0db1681c51791b0',
    messagingSenderId: '833820909585',
    projectId: 'mailforfinal-7bf12',
    storageBucket: 'mailforfinal-7bf12.firebasestorage.app',
    iosBundleId: 'com.example.mail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyx0jSPQ5IaTsUQbpaDrDwPnRP7qCWGnU',
    appId: '1:833820909585:web:c0409b2ed68682711791b0',
    messagingSenderId: '833820909585',
    projectId: 'mailforfinal-7bf12',
    authDomain: 'mailforfinal-7bf12.firebaseapp.com',
    storageBucket: 'mailforfinal-7bf12.firebasestorage.app',
  );
}
